import Header from '@/components/Header';
import ErudaInit from './eruda-init';
import UserProviderWrapper from './user-provider';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { styles as typescaleStyles } from '@material/web/typography/md-typescale-styles.js';

if (typeof window !== 'undefined') {
  document.adoptedStyleSheets.push(typescaleStyles.styleSheet);
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="/material-symbols.css" />
      </head>
      <UserProviderWrapper>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <ErudaInit />
          <Header />
          {children}
        </body>
      </UserProviderWrapper>
    </html>
  );
}
