export const ALLOWED_EVENT_TYPES = [
    "2pt Shot Attempt",
    "2pt Shot Made",
    "2pt Shot Missed",
    "3pt Shot Attempt",
    "3pt Shot Made",
    "3pt Shot Missed",
    "Assist",
    "Block",
    "Defensive Rebound",
    "Dribble",
    "End of Game",
    "End of Period",
    "Flagrant Foul",
    "Foul",
    "Free Throw Attempt",
    "Free Throw Made",
    "Free Throw Missed",
    "Game Start",
    "Jump Ball",
    "Jump Ball Possession",
    "Offensive Foul",
    "Offensive Rebound",
    "Out of Bounds",
    "Pass",
    "Period Start",
    "Personal Foul",
    "Possession Change",
    "Rebound",
    "Shooting Foul",
    "Steal",
    "Substitution",
    "Technical Foul",
    "Team Rebound",
    "Timeout Taken",
    "Turnover",
    "Violation"
];

// Create a Set of uppercase event types for efficient, case-insensitive lookups.
export const UPPERCASE_ALLOWED_EVENT_TYPES = new Set(ALLOWED_EVENT_TYPES.map(t => t.toUpperCase()));
